# Generated by Django 3.1.7 on 2021-07-20 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210719_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResources',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('visible_only_to_event_host', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=5000, verbose_name='Add URL')),
                ('favicon_path', models.URLField(blank=True, max_length=500, null=True, verbose_name='Favicon URL')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
