# Generated by Django 3.1.7 on 2021-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventresources'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
