# Generated by Django 3.1.7 on 2021-08-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210805_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='private_or_public',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Private'), (2, 'Public')], null=True),
        ),
    ]
