# Generated by Django 3.1.7 on 2021-08-25 12:27

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20210818_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.company_event_image_file_name),
        ),
    ]
