# Generated by Django 3.1.7 on 2021-08-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20210823_1027'),
        ('event', '0010_auto_20210825_1227'),
    ]

    operations = [
    ]
