# Generated by Django 3.1.7 on 2021-09-14 15:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_merge_20210827_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_quill.fields.QuillField(max_length=10000),
        ),
    ]
