# Generated by Django 3.1.7 on 2021-10-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20210914_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_accept_requests',
            field=models.BooleanField(default=False),
        ),
    ]
